server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true